
image: registry.git.vgregion.se/spinalytics/spinalytics-docker-image
before_script:
  - apt-get update && apt-get install -y curl build-essential git pre-commit
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="$HOME/.local/bin:$PATH"
  - poetry config virtualenvs.in-project true
  - python tasks.py install-dev
stages:
  - check
  - test
  - build
check:
  stage: check
  script:
    - python tasks.py check
test:
  stage: test
  script:
    - python tasks.py test
build:
  stage: build
  script:
    - python tasks.py build
  artifacts:
    paths:
      - dist/
