import logging
from pathlib import Path
import subprocess
import tempfile

from fileformats.medimage import NiftiGz
from pydra.compose import python


logger = logging.getLogger(__name__)


@python.define(outputs=["label_map", "levels"])
def run_totalspineseg(
    image: NiftiGz,
    data_dir: Path,
    device: str = "cpu",
    iso: bool = False,
    no_stalling: bool = False,
    max_workers: int | None = None,
    max_workers_nnunet: int | None = None,
    quiet: bool = False,
    executable: str = "totalspineseg",
) -> tuple[NiftiGz, NiftiGz]:
    """
    Run TotalSpineSeg segmentation on a single image.

    Parameters
    ----------
    image : NiftiGz
        Input image file to be segmented.
    data_dir : Path
        Directory containing TotalSpineSeg data and models.
    device : str, optional
        Device to run inference on (e.g., "cpu", "cuda"), by default "cpu".
    iso : bool, optional
        Whether to use isotropic resampling, by default False.
    no_stalling : bool, optional
        Whether to disable stalling behavior, by default False.
    max_workers : int | None, optional
        Maximum number of workers for parallel processing, by default None.
    max_workers_nnunet : int | None, optional
        Maximum number of workers for nnUNet, by default None.
    quiet : bool, optional
        Whether to suppress logging output, by default False.
    executable : str, optional
        Name of the TotalSpineSeg executable, by default "totalspineseg".

    Returns
    -------
    tuple[NiftiGz, NiftiGz]
        A tuple containing the output label map file and levels map file.

    Raises
    ------
    subprocess.CalledProcessError
        If the TotalSpineSeg process fails with non-zero exit code.
    FileNotFoundError
        If the expected output files are not generated by TotalSpineSeg.
    """

    with tempfile.TemporaryDirectory(prefix="totalspineseg-") as tempdir:
        intermediate_output = Path(tempdir)

        cmd = [
            executable,
            str(Path(image)),
            str(intermediate_output),
        ]

        if iso:
            cmd.append("--iso")

        cmd.extend(
            [
                "--data-dir",
                str(data_dir),
            ]
        )

        if no_stalling:
            cmd.append("--no-stalling")

        if max_workers is not None:
            cmd.extend(
                [
                    "--max-workers",
                    str(max_workers),
                ]
            )

        if max_workers_nnunet is not None:
            cmd.extend(
                [
                    "--max-workers-nnunet",
                    str(max_workers_nnunet),
                ]
            )

        if device is not None:
            cmd.extend(
                [
                    "--device",
                    device,
                ]
            )

        if quiet:
            cmd.append("--quiet")

        logger.info("Running: %s", " ".join(cmd))

        with subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        ) as process:
            if process.stdout is not None:
                for line in process.stdout:
                    if not quiet:
                        logger.info(line.rstrip())

            returncode = process.wait()

        if returncode != 0:
            raise subprocess.CalledProcessError(
                returncode,
                cmd,
            )

        # Copy output files from TotalSpineSeg to output paths

        generated_label_map = NiftiGz(intermediate_output / "step2_output" / image.name)
        generated_levels_map = NiftiGz(
            intermediate_output / "step1_levels" / image.name
        )

        if not generated_label_map.is_file():
            raise FileNotFoundError(
                f"TotalSpineSeg did not generate the expected label map: {str(generated_label_map)}"
            )

        if not generated_levels_map.is_file():
            raise FileNotFoundError(
                f"TotalSpineSeg did not generate the expected levels map: {str(generated_levels_map)}"
            )

        label_map = generated_label_map.move(
            dest_dir=Path.cwd(), stem_suffix="dseg", overwrite=True
        )
        levels = generated_levels_map.move(
            dest_dir=Path.cwd(), stem_suffix="levels", overwrite=True
        )

        logger.info(f"File: {str(label_map)} created")
        logger.info(f"File: {str(levels)} created")

        return label_map, levels
