from importlib.metadata import version
import logging
from pathlib import Path
import shutil
import subprocess
import tempfile

from fileformats.generic import Directory, File

from pydra.compose import workflow, python

import spinemira
from spinemira.tasks.mids import initialize_derivative, query_mids, resolve_derivative
from spinemira.pipelines.config import with_cli_config
from spinemira.core.logging import setup_logging


logger = logging.getLogger(__name__)


@python.define(outputs=["label_map", "levels"])
def run_totalspineseg(
    image: File,
    output_label_map: Path,
    output_levels: Path,
    data_dir: Path,
    device: str = "cpu",
    iso: bool = False,
    no_stalling: bool = False,
    max_workers: int | None = None,
    max_workers_nnunet: int | None = None,
    quiet: bool = False,
    executable: str = "totalspineseg",
    overwrite: bool = False,
) -> tuple[File, File]:
    """
    Run TotalSpineSeg segmentation on a single image.

    Parameters
    ----------
    image : File
        Input image file to be segmented.
    output_label_map : Path
        Path where the output label map will be saved.
    output_levels : Path
        Path where the output levels map will be saved.
    data_dir : Path
        Directory containing TotalSpineSeg data and models.
    device : str, optional
        Device to run inference on (e.g., "cpu", "cuda"), by default "cpu".
    iso : bool, optional
        Whether to use isotropic resampling, by default False.
    no_stalling : bool, optional
        Whether to disable stalling behavior, by default False.
    max_workers : int | None, optional
        Maximum number of workers for parallel processing, by default None.
    max_workers_nnunet : int | None, optional
        Maximum number of workers for nnUNet, by default None.
    quiet : bool, optional
        Whether to suppress logging output, by default False.
    executable : str, optional
        Name of the TotalSpineSeg executable, by default "totalspineseg".
    overwrite : bool, optional
        Whether to overwrite existing output files, by default False.

    Returns
    -------
    tuple[File, File]
        A tuple containing the output label map file and levels map file.

    Raises
    ------
    subprocess.CalledProcessError
        If the TotalSpineSeg process fails with non-zero exit code.
    FileNotFoundError
        If the expected output files are not generated by TotalSpineSeg.
    """

    output_exists = output_label_map.exists() and output_levels.exists()

    if not output_exists or overwrite:
        with tempfile.TemporaryDirectory(prefix="totalspineseg-") as tempdir:
            intermediate_output = Path(tempdir)

            cmd = [
                executable,
                str(Path(image)),
                str(intermediate_output),
            ]

            if iso:
                cmd.append("--iso")

            cmd.extend(
                [
                    "--data-dir",
                    str(data_dir),
                ]
            )

            if no_stalling:
                cmd.append("--no-stalling")

            if max_workers is not None:
                cmd.extend(
                    [
                        "--max-workers",
                        str(max_workers),
                    ]
                )

            if max_workers_nnunet is not None:
                cmd.extend(
                    [
                        "--max-workers-nnunet",
                        str(max_workers_nnunet),
                    ]
                )

            if device is not None:
                cmd.extend(
                    [
                        "--device",
                        device,
                    ]
                )

            if quiet:
                cmd.append("--quiet")

            logger.info("Running: %s", " ".join(cmd))

            with subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
            ) as process:
                if process.stdout is not None:
                    for line in process.stdout:
                        if not quiet:
                            logger.info(line.rstrip())

                returncode = process.wait()

            if returncode != 0:
                raise subprocess.CalledProcessError(
                    returncode,
                    cmd,
                )

            # Copy output files from TotalSpineSeg to output paths

            generated_label_map = File(
                intermediate_output / "step2_output" / image.name
            )
            generated_levels_map = File(
                intermediate_output / "step1_levels" / image.name
            )

            if not generated_label_map.is_file():
                raise FileNotFoundError(
                    f"TotalSpineSeg did not generate the expected label map: {str(generated_label_map)}"
                )

            if not generated_levels_map.is_file():
                raise FileNotFoundError(
                    f"TotalSpineSeg did not generate the expected levels map: {str(generated_levels_map)}"
                )

            output_label_map.parent.mkdir(parents=True, exist_ok=True)
            output_levels.parent.mkdir(parents=True, exist_ok=True)

            shutil.move(generated_label_map, output_label_map)
            shutil.move(generated_levels_map, output_levels)

            logger.info(f"File: {str(output_label_map)} created")
            logger.info(f"File: {str(output_levels)} created")
    else:
        logger.info(
            f"Output label map: {str(output_label_map)} and/ or levels: {str(output_levels)} exists. Skipping."
        )

    return File(output_label_map), File(output_levels)


@python.define(outputs=["query"])
def build_image_query(base: str, image_weight: str) -> str:
    """
    Build a query string for image filtering.

    Parameters
    ----------
    base : str
        Base query string to build upon.
    image_weight : str
        Image weight/suffix to filter by (e.g., "T1w", "T2w").

    Returns
    -------
    str
        A query string that combines the base query with additional filters
        for non-sidecar files with the specified suffix.
    """
    extra = [
        "~is_sidecar",
        f"`suffix` == '{image_weight}'",
    ]
    return " and ".join([base, *extra])


@workflow.define(outputs=["label_map", "levels"])
def segment_dataset(
    dataset_root: Directory,
    image_query: str,
    output_derivative_name: str,
    image_weight: str,
    totalspineseg_data_dir: Path,
    overwrite: bool = False,
    device: str = "cpu",
    totalspineseg_quiet: bool = False,
):
    """
    Create a workflow for segmenting a dataset using TotalSpineSeg.

    Parameters
    ----------
    dataset_root : Directory
        Root directory of the dataset to process.
    image_query : str
        Base query string to filter images.
    output_derivative_name : str
        Name of the output derivative folder.
    image_weight : str
        Image weight/suffix to filter by (e.g., "T1w", "T2w").
    totalspineseg_data_dir : Path
        Directory containing TotalSpineSeg data and models.
    overwrite : bool, optional
        Whether to overwrite existing output files, by default False.
    device : str, optional
        Device to run inference on (e.g., "cpu", "cuda"), by default "cpu".
    totalspineseg_quiet : bool, optional
        Whether to suppress TotalSpineSeg logging output, by default False.

    Returns
    -------
    tuple[Any, Any]
        A tuple containing the label map and levels outputs from the workflow.
    """

    initialized_derivative = workflow.add(
        initialize_derivative(
            dataset_root=dataset_root,
            derivative_name=output_derivative_name,
            pipeline_name="TotalSpineSeg - spinemira",
            pipeline_version=version(spinemira.__package__),
        ),
        name="initialize_derivative",
    )

    mids_query = workflow.add(
        build_image_query(base=image_query, image_weight=image_weight),
        name="build_mids_query",
    )

    images = workflow.add(
        query_mids(
            dataset_root=dataset_root,
            query=mids_query.query,
        ),
        name="query_dataset",
    )

    out_label_maps = workflow.add(
        resolve_derivative(
            derivative_folder=initialized_derivative.folder, suffix="dseg"
        )
        .split(file=images.files)
        .combine("file"),
        "resolve_destination_label_maps",
    )

    out_levels = workflow.add(
        resolve_derivative(
            derivative_folder=initialized_derivative.folder, suffix="levels"
        )
        .split(file=images.files)
        .combine("file"),
        "resolve_destination_levels",
    )

    segmented = workflow.add(
        run_totalspineseg(
            data_dir=totalspineseg_data_dir,
            device=device,
            quiet=totalspineseg_quiet,
            overwrite=overwrite,
        )
        .split(
            ("image", "output_label_map", "output_levels"),
            image=images.files,
            output_label_map=out_label_maps.path,
            output_levels=out_levels.path,
        )
        .combine("image"),
        "run_segmentation",
    )

    return segmented.label_map, segmented.levels


@with_cli_config()
def run_workflow(
    dataset_root: Path,
    image_query: str,
    output_derivative_name: str,
    image_weight: str,
    totalspineseg_data_dir: Path,
    overwrite: bool = False,
    device: str = "cpu",
    totalspineseg_quiet: bool = False,
    rerun: bool = False,
):
    """
    Execute the TotalSpineSeg segmentation workflow.

    Parameters
    ----------
    dataset_root : Path
        Root directory of the dataset to process.
    image_query : str
        Base query string to filter images.
    output_derivative_name : str
        Name of the output derivative folder.
    image_weight : str
        Image weight/suffix to filter by (e.g., "T1w", "T2w").
    totalspineseg_data_dir : Path
        Directory containing TotalSpineSeg data and models.
    overwrite : bool, optional
        Whether to overwrite existing output files, by default False.
    device : str, optional
        Device to run inference on (e.g., "cpu", "cuda"), by default "cpu".
    totalspineseg_quiet : bool, optional
        Whether to suppress TotalSpineSeg logging output, by default False.
    rerun : bool, optional
        Whether to rerun the workflow even if outputs exist, by default False.
    """

    dataset_root_dir = Directory(Path(dataset_root).resolve())

    segment_dataset_workflow = segment_dataset(
        dataset_root=dataset_root_dir,
        image_query=image_query,
        output_derivative_name=output_derivative_name,
        image_weight=image_weight,
        totalspineseg_data_dir=totalspineseg_data_dir,
        overwrite=overwrite,
        device=device,
        totalspineseg_quiet=totalspineseg_quiet,
    )

    segment_dataset_workflow(worker="debug", rerun=rerun)


if __name__ == "__main__":
    setup_logging(filename="segmentation_pipeline.log")
    run_workflow()
